UCS420 (Cognitive Computing) - Assignment 5

Question 1

In [ ]:
import numpy as np

arr = np.array([5,8,10,14,19])

print("Original Array: ", arr)
print("Addition of 2: ", arr + 2)
print("Multiplication by 3: ", arr * 3)
print("Division by 2: ", arr / 2)

Original Array:  [ 5  8 10 14 19]
Addition of 2:  [ 7 10 12 16 21]
Multiplication by 3:  [15 24 30 42 57]
Division by 2:  [2.5 4.  5.  7.  9.5]


Question 2

In [ ]:
import numpy as np

arr = np.array([1,2,3,6,4,5])

print("Original Array: ",arr)
print("Reversed Array: ",arr[::-1])

Original Array:  [1 2 3 6 4 5]
Reversed Array:  [5 4 6 3 2 1]


In [ ]:
import numpy as np

x = np.array([1,2,3,4,5,1,2,1,1,1])
values, counts = np.unique(x, return_counts = True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]

print("Most Frequent Value: ", most_frequent)
print("Frequency: ", np.max(counts))
print("Indices: ", indices)


y = np.array([1,1,1,2,3,4,2,4,3,3])
values,counts = np.unique(y, return_counts = True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]

print("Most Frequent Value: ", most_frequent)
print("Frequency: ", np.max(counts))
print("Indices: ", indices)

Most Frequent Value:  1
Frequency:  5
Indices:  [0 5 7 8 9]
Most Frequent Value:  1
Frequency:  3
Indices:  [0 1 2]


Question 3

In [1]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


Question 4

In [2]:
import numpy as np

lavdeep = np.linspace(10, 100, 25)

print("Array:", lavdeep)
print("Dimensions:", lavdeep.ndim)
print("Shape:", lavdeep.shape)
print("Total Elements:", lavdeep.size)
print("Data Type:", lavdeep.dtype)
print("Total Bytes:", lavdeep.nbytes)

transposed = lavdeep.reshape(25, 1)
print("Transpose using reshape():\n", transposed)

print("Transpose using T attribute:\n", lavdeep.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Total Bytes: 200
Transpose using reshape():
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Question 5

In [3]:
import numpy as np

ucs420_lavdeep = np.array([[10, 20, 30, 40],
                           [50, 60, 70, 80],
                           [90, 15, 20, 35]])

print("Original Array:\n", ucs420_lavdeep)
print("Mean:", np.mean(ucs420_lavdeep))
print("Median:", np.median(ucs420_lavdeep))
print("Maximum:", np.max(ucs420_lavdeep))
print("Minimum:", np.min(ucs420_lavdeep))
print("Unique Elements:", np.unique(ucs420_lavdeep))

reshaped_ucs420_lavdeep = ucs420_lavdeep.reshape(4, 3)
print("Reshaped Array (4x3):\n", reshaped_ucs420_lavdeep)

resized_ucs420_lavdeep = np.resize(ucs420_lavdeep, (2, 3))
print("Resized Array (2x3):\n", resized_ucs420_lavdeep)

Original Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
